### ISSUE TITLE
ruby audit works under bundler, but not stand-alone

### ISSUE THREAD

**Issue by Adre** [civisanalytics/ruby_audit#18]
Hi,

I'm having some issues with the direct gem install approach when I'm not using bundler.

For context, this was identified while I was trying to move away from manually calling the command locally to get it running under ci without requiring ruby_audit to be an application dependency.

It's not a massive hardship in my case to just scope it to `:test` in the Gemfile, but I thought I'd raise it in case you weren't aware (or I'm doing something dumb):

## Actual behaviour
When manually installing the gem as follows I encounter an error when performing the check

```
# gem install ruby_audit
Fetching ruby_audit-2.0.0.gem
Successfully installed ruby_audit-2.0.0
1 gem installed

# ruby-audit check
Traceback (most recent call last):
	3: from /usr/local/bundle/bin/ruby-audit:23:in `<main>'
	2: from /usr/local/bundle/bin/ruby-audit:23:in `load'
	1: from /usr/local/bundle/gems/ruby_audit-2.0.0/exe/ruby-audit:4:in `<top (required)>'
/usr/local/bundle/gems/ruby_audit-2.0.0/exe/ruby-audit:4:in `require': cannot load such file -- ruby_audit (LoadError)
```

On the other hand, when installing the gem via bundler the check completes fine.

## Expected behaviour

I can install the gem directly and execute the check without needing to use bundler.

**Comment by mikesaelim** [comment]
Hey @Adre, sorry about the issues you've experienced.

ruby_audit has bundler as a transitive dependency, through [bundler-audit](https://github.com/rubysec/bundler-audit).  I've decoupled some of our code from bundler-audit recently, but I'm not sure we'll fully remove the dependency altogether, so I guess the bundler dependency will remain for a while.

Scoping this gem and bundler-audit to `:test` in the Gemfile is a great way to run this in your CI and not include it in the production environment - that's what we do with our code!

**Comment by Adre** [comment]
Thanks for the response @mikesaelim

As I mentioned before, not a huge issue and there's a decent enough workaround, just an FYI that there's an issue for users who follow the 'Or install it yourself as' path in the README.

I wonder if it's worth updating the README for clarification?

**Comment by mikesaelim** [comment]
I think it could be.  How does this change sound?  #19

**Comment by Adre** [comment]
Looks good to me.

Feel free to close this ticket unless you feel it's useful to keep around.

Thanks for your help!

**Comment by mikesaelim** [comment]
Thanks for reporting the issue!
