### ISSUE TITLE
Bug: doesn't check rubygems anymore

### ISSUE THREAD

**Issue by adamzapasnik** [civisanalytics/ruby_audit#28]
The file structure of https://github.com/rubysec/ruby-advisory-db has changed. `libraries` dir was removed and its files moved to `gems/rubygems-update` dir. Therefore existing code doesn't work with the new file structure.

Probably there should be a scheduled Github action that runs tests every week against https://github.com/rubysec/ruby-advisory-db  🤔

**Comment by adamzapasnik** [comment]
This has been fixed by https://github.com/civisanalytics/ruby_audit/pull/35, right @mikesaelim @leanne73? Feel free to close it.

**Comment by mikesaelim** [comment]
Oh whoa, I completely missed this issue!  Sorry about that, looks like you had identified this problem first, and we didn't see it.  😞 

You're right, this should be fixed by #35 and released in v2.3.1.  I don't have the power to close issues here anymore, can you or @leanne73 do it?

**Comment by adamzapasnik** [comment]
No worries, good it's fixed now, thanks ;) 🙏
