### ISSUE TITLE
Could not find gem 'ruby_audit (>= 2.2)'

### ISSUE THREAD

**Issue by RobWu** [civisanalytics/ruby_audit#30]
Version 2.2 is released. https://github.com/civisanalytics/ruby_audit/releases/tag/v2.2.0
But looks like it is not available yet.

When running `bundle update ruby_audit`
```
Fetching gem metadata from https://rubygems.org/........

Could not find gem 'ruby_audit (>= 2.2)' in rubygems repository https://rubygems.org/ or installed locally.

The source contains the following gems matching 'ruby_audit':
  * ruby_audit-1.0.0
  * ruby_audit-1.0.1
  * ruby_audit-1.1.0
  * ruby_audit-1.2.0
  * ruby_audit-1.3.0
  * ruby_audit-2.0.0
  * ruby_audit-2.1.0
```

**Comment by jydli** [comment]
Thank you for bringing this to our attention. It's being worked on and I will update this issue once it's been resolved

**Comment by jydli** [comment]
The new version should now be available here: https://rubygems.org/gems/ruby_audit
